[package]
name = "structural-typesystem"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
log = "0.4.17"
simple_logger = "4.2.0"
symbolic_expressions = "5.0.3"
petgraph = "0.6.3"
ptree = "0.4.0"
ast = { path = "../ast" }
tracing = "0.1.40"
