[package]
name = "hindley-milner"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.17"
env_logger = "0.9.0"
symbolic_expressions = "5.0.3"
anyhow = "1"
structural-typesystem = { path = "../structural-typesystem" }
ast = { path = "../ast" }