[package]
name = "interpreter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
symbolic_expressions = "5.0.3"
anyhow = "1"
structural-typesystem = { path = "../structural-typesystem" }
hindley-milner = { path = "../hindley-milner" }